language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
before_script: "echo 'Ready to test'"
script:
  - npm test
after_success:
  - npm run coverage
  - "echo 'Tests complete'"
before_deploy: "echo 'Ready to deploy'"
deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p
  skip_cleanup: true
  on:
    branch: master
    tags: true
after_deploy: "echo 'Deployment complete'"